<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.7                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2017                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2017
 *
 * Generated from /home/erik/buildkit/build/fzfddev/sites/default/files/civicrm/ext/de.forumzfd.apiprocessing/xml/schema/CRM/Apiprocessing/FzfdMandate.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:cb60a951366bf5d36d48cdc812e55175)
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
/**
 * CRM_Apiprocessing_DAO_FzfdMandate constructor.
 */
class CRM_Apiprocessing_DAO_FzfdMandate extends CRM_Core_DAO {
  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_fzfd_sdd_mandate';
  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var boolean
   */
  static $_log = true;
  /**
   * Unique FzfdMandate ID (temp_id)
   *
   * @var int unsigned
   */
  public $id;
  /**
   * FK to FzfdTemp
   *
   * @var int unsigned
   */
  public $temp_id;
  /**
   * Origin of this Contribution.
   *
   * @var string
   */
  public $source;
  /**
   * Iban of the debtor
   *
   * @var string
   */
  public $iban;
  /**
   * BIC of the debtor
   *
   * @var string
   */
  public $bic;
  /**
   * RCUR for recurrent (default), OOFF for one-shot
   *
   * @var string
   */
  public $type;
  /**
   * Status of the mandate (OOFF, FRST, RCUR)
   *
   * @var string
   */
  public $status;
  /**
   * Financial Type ID
   *
   * @var int unsigned
   */
  public $financial_type_id;
  /**
   * Amount
   *
   * @var float
   */
  public $amount;
  /**
   * 3 character string for currency
   *
   * @var string
   */
  public $currency;
  /**
   * The campaign for which this contribution has been triggered.
   *
   * @var int unsigned
   */
  public $campaign_id;
  /**
   * Day in the period when the payment should be charged e.g. 1st of month, 15th etc.
   *
   * @var int unsigned
   */
  public $cycle_day;
  /**
   * Time units for recurrence of payment.
   *
   * @var string
   */
  public $frequency_unit;
  /**
   * Number of time units for recurrence of payment.
   *
   * @var int unsigned
   */
  public $frequency_interval;
  /**
   * The date the first scheduled recurring contribution occurs.
   *
   * @var datetime
   */
  public $start_date;
  /**
   * Class constructor.
   */
  function __construct() {
    $this->__table = 'civicrm_fzfd_sdd_mandate';
    parent::__construct();
  }
  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName() , 'temp_id', 'civicrm_fzfd_temp', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = array(
        'id' => array(
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique FzfdMandate ID (temp_id)',
          'required' => true,
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'temp_id' => array(
          'name' => 'temp_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to FzfdTemp',
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'source' => array(
          'name' => 'source',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Contribution Source') ,
          'description' => 'Origin of this Contribution.',
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'iban' => array(
          'name' => 'iban',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Iban') ,
          'description' => 'Iban of the debtor',
          'required' => false,
          'maxlength' => 42,
          'size' => CRM_Utils_Type::BIG,
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'bic' => array(
          'name' => 'bic',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Bic') ,
          'description' => 'BIC of the debtor',
          'maxlength' => 11,
          'size' => CRM_Utils_Type::TWELVE,
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'type' => array(
          'name' => 'type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Type') ,
          'description' => 'RCUR for recurrent (default), OOFF for one-shot',
          'required' => true,
          'maxlength' => 4,
          'size' => CRM_Utils_Type::FOUR,
          'default' => 'RCUR',
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'status' => array(
          'name' => 'status',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Status') ,
          'description' => 'Status of the mandate (OOFF, FRST, RCUR)',
          'required' => true,
          'maxlength' => 8,
          'size' => CRM_Utils_Type::EIGHT,
          'default' => 'INIT',
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'financial_type_id' => array(
          'name' => 'financial_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Financial Type ID',
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'amount' => array(
          'name' => 'amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => ts('Amount') ,
          'description' => 'Amount',
          'precision' => array(
            20,
            2
          ) ,
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'currency' => array(
          'name' => 'currency',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Currency') ,
          'description' => '3 character string for currency',
          'maxlength' => 3,
          'size' => CRM_Utils_Type::FOUR,
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'campaign_id' => array(
          'name' => 'campaign_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Campaign') ,
          'description' => 'The campaign for which this contribution has been triggered.',
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'cycle_day' => array(
          'name' => 'cycle_day',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Number of Cycle Day') ,
          'description' => 'Day in the period when the payment should be charged e.g. 1st of month, 15th etc.',
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'frequency_unit' => array(
          'name' => 'frequency_unit',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Frequency Unit') ,
          'description' => 'Time units for recurrence of payment.',
          'maxlength' => 8,
          'size' => CRM_Utils_Type::EIGHT,
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'frequency_interval' => array(
          'name' => 'frequency_interval',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Interval (number of units)') ,
          'description' => 'Number of time units for recurrence of payment.',
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
        'start_date' => array(
          'name' => 'start_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Recurring Contribution Started Date') ,
          'description' => 'The date the first scheduled recurring contribution occurs.',
          'table_name' => 'civicrm_fzfd_sdd_mandate',
          'entity' => 'FzfdMandate',
          'bao' => 'CRM_Apiprocessing_DAO_FzfdMandate',
          'localizable' => 0,
        ) ,
      );
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }
  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName() {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog() {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'fzfd_sdd_mandate', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'fzfd_sdd_mandate', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of indices
   */
  public static function indices($localize = TRUE) {
    $indices = array();
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }
}
