-- +--------------------------------------------------------------------+
-- | CiviCRM version 4.7                                                |
-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC (c) 2004-2017                                |
-- +--------------------------------------------------------------------+
-- | This file is a part of CiviCRM.                                    |
-- |                                                                    |
-- | CiviCRM is free software; you can copy, modify, and distribute it  |
-- | under the terms of the GNU Affero General Public License           |
-- | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
-- |                                                                    |
-- | CiviCRM is distributed in the hope that it will be useful, but     |
-- | WITHOUT ANY WARRANTY; without even the implied warranty of         |
-- | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
-- | See the GNU Affero General Public License for more details.        |
-- |                                                                    |
-- | You should have received a copy of the GNU Affero General Public   |
-- | License and the CiviCRM Licensing Exception along                  |
-- | with this program; if not, contact CiviCRM LLC                     |
-- | at info[AT]civicrm[DOT]org. If you have questions about the        |
-- | GNU Affero General Public License or the licensing of CiviCRM,     |
-- | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--


-- +--------------------------------------------------------------------+
-- | CiviCRM version 4.7                                                |
-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC (c) 2004-2017                                |
-- +--------------------------------------------------------------------+
-- | This file is a part of CiviCRM.                                    |
-- |                                                                    |
-- | CiviCRM is free software; you can copy, modify, and distribute it  |
-- | under the terms of the GNU Affero General Public License           |
-- | Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
-- |                                                                    |
-- | CiviCRM is distributed in the hope that it will be useful, but     |
-- | WITHOUT ANY WARRANTY; without even the implied warranty of         |
-- | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
-- | See the GNU Affero General Public License for more details.        |
-- |                                                                    |
-- | You should have received a copy of the GNU Affero General Public   |
-- | License and the CiviCRM Licensing Exception along                  |
-- | with this program; if not, contact CiviCRM LLC                     |
-- | at info[AT]civicrm[DOT]org. If you have questions about the        |
-- | GNU Affero General Public License or the licensing of CiviCRM,     |
-- | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the exisiting tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_fzfd_temp`;
DROP TABLE IF EXISTS `civicrm_fzfd_sdd_mandate`;
DROP TABLE IF EXISTS `civicrm_fzfd_contribution`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_fzfd_temp
-- *
-- * Table with FzfdDonations not confirmed yet
-- *
-- *******************************************************/
CREATE TABLE `civicrm_fzfd_temp` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique FzfdTemp ID',
     `contact_id` int unsigned    COMMENT 'FK to Contact',
     `payment_instrument_id` int unsigned    ,
     `date_created` datetime
,
        PRIMARY KEY (`id`)


,          CONSTRAINT FK_civicrm_fzfd_temp_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)    ;

-- /*******************************************************
-- *
-- * civicrm_fzfd_contribution
-- *
-- * Table to hold contributions that have not been confirmed yet
-- *
-- *******************************************************/
CREATE TABLE `civicrm_fzfd_contribution` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique FzfdContribution ID',
     `temp_id` int unsigned    COMMENT 'FK to FzfdTemp',
     `financial_type_id` int unsigned    COMMENT 'Financial Type ID',
     `payment_instrument_id` int unsigned    COMMENT 'Payment Instrument ID',
     `total_amount` decimal(20,2)    COMMENT 'Total amount of this contribution',
     `currency` varchar(3)    COMMENT '3 character string for currency',
     `source` varchar(255)    COMMENT 'Origin of this Contribution.',
     `campaign_id` int unsigned    COMMENT 'The campaign for which this contribution has been triggered.' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_fzfd_contribution_temp_id FOREIGN KEY (`temp_id`) REFERENCES `civicrm_fzfd_temp`(`id`) ON DELETE CASCADE  
)    ;

-- /*******************************************************
-- *
-- * civicrm_fzfd_sdd_mandate
-- *
-- * Table to hold mandates that have not been confirmed yet
-- *
-- *******************************************************/
CREATE TABLE `civicrm_fzfd_sdd_mandate` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique FzfdMandate ID (temp_id)',
     `temp_id` int unsigned    COMMENT 'FK to FzfdTemp',
     `source` varchar(255)    COMMENT 'Origin of this Contribution.',
     `iban` varchar(42) NULL   COMMENT 'Iban of the debtor',
     `bic` varchar(11)    COMMENT 'BIC of the debtor',
     `type` varchar(4) NOT NULL  DEFAULT "RCUR" COMMENT 'RCUR for recurrent (default), OOFF for one-shot',
     `status` varchar(8) NOT NULL  DEFAULT "INIT" COMMENT 'Status of the mandate (OOFF, FRST, RCUR)',
     `financial_type_id` int unsigned    COMMENT 'Financial Type ID',
     `amount` decimal(20,2)    COMMENT 'Amount',
     `currency` varchar(3)    COMMENT '3 character string for currency',
     `campaign_id` int unsigned    COMMENT 'The campaign for which this contribution has been triggered.',
     `cycle_day` int unsigned    COMMENT 'Day in the period when the payment should be charged e.g. 1st of month, 15th etc.',
     `frequency_unit` varchar(8)    COMMENT 'Time units for recurrence of payment.',
     `frequency_interval` int unsigned    COMMENT 'Number of time units for recurrence of payment.',
     `start_date` datetime    COMMENT 'The date the first scheduled recurring contribution occurs.' 
,
        PRIMARY KEY (`id`)
 
 
,          CONSTRAINT FK_civicrm_fzfd_sdd_mandate_temp_id FOREIGN KEY (`temp_id`) REFERENCES `civicrm_fzfd_temp`(`id`) ON DELETE CASCADE  
)    ;

 